config/routes.rb
Rails.application.routes.draw do
  resources :reviews, except: [:index, :show]
  resources :comments, except: [:update, :edit, :show]

  root "games#index"
  resources :games, only: [:index]
  get '/games/results', to: 'games#results', as: "results"
  get '/games/suggested', to: 'games#suggested', as: "suggested"

  resources :sessions, only: [:create]
  resources :users, except: [:update, :edit, :delete, :new]

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  get 'register' => 'users#new'
  post 'users' => 'users#create'

  resources :ownerships, only: [:create, :destroy]

  resources :games

  resources :groups, only: [:new, :create, :show]

  resources :memberships, only: [:new, :create, :delete]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships, foreign_key: :member_id
  has_many :groups, through: :memberships
  has_many :created_groups, class_name: "Group", foreign_key: :creator_id
  has_many :comments, foreign_key: :commenter_id
  has_many :reviews, foreign_key: :reviewer_id
  has_many :ownerships, foreign_key: :owner_id
  has_many :owned_games, through: :ownerships, source: :game
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, on: :create
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      # redirect_to register_path
      redirect_to user_path id: session[:user_id]
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @owned_games = Ownership.where(owner_id: @user.id)
    # Need to iterate and get each ownership.game_id
    @users_games_hash = {}

    @owned_games.each do |ownership|
      url ="http://www.boardgamegeek.com/xmlapi/boardgame/#{ownership.game_id}"
      xml_data = open(url)
      read_file = xml_data
      @response_body = Crack::XML.parse(read_file)
      game = @response_body["boardgames"]["boardgame"]
      game["name"].class == Array ? game_name = game["name"][0] : game_name = game["name"]
      @users_games_hash[game_name] = [game["thumbnail"], ownership.game_id]
    end

  end

private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <span><%= pluralize(@user.errors.count, "error") %></span>
  <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
<% end %>

<%= render "form" %>

app/views/users/show.html.erb
<div class="container">

  <div class="user-details">

    <div class="profile-picture">
      <img src="http://i.imgur.com/8PKlHjh.jpg?1">
    </div>

    <div class="user-info">
      <h2><%= @user.personal_info %></h2>
    </div>
  </div>

  <div class="user-groups">
    <% @user.groups.each do |group| %>
      <div class="individual-group">
        <h3><a href="/groups/<%= group.id %>"><%= group.name %> </a></h3>
        <ul>
          <% group.members.each do |member| %>
          <li> <%= member.username %> </li>
          <% end %>
        </ul>
        <h4>Popular Games</h4>
        <ul>
          <% group.group_games.each do |game| %>
            <li><a href="<%= game_path(game) %>"><%= game.name %></a></li>
          <% end %>
        </ul>


        <h4>Last Meetup</h4>

      </div>
    <% end %>
    <div class="new-group-button">
      <%= link_to new_group_path do %>
        <i class="fa fa-plus" id="plus-big" aria-hidden="true"></i>
        <h4>New Group</h4>
      <% end %>
    </div>
  </div>



  <div class="user-games">

    <div class="new-game-button">
      <%= link_to suggested_path do %>
        <i class="fa fa-plus" id="plus-big" aria-hidden="true"></i>
        <h4>New Game</h4>
      <% end %>
    </div>

    <% @users_games_hash.each do |game_name, game_pic_n_number| %>
      <div class="individual-game">
        <div class="game-icon">
          <img src=" <%= game_pic_n_number[0] %> ">
        </div>
        <h4>
          <a href="/games/<%= game_pic_n_number[1] %>"><%= game_name %></a>
        </h4>
      </div>
    <% end %>
  </div>
</div>