config/routes.rb
Rails.application.routes.draw do
  resources :reviews, except: [:index, :show]
  resources :comments, except: [:update, :edit, :show]

  root "games#index"
  resources :games, only: [:index]
  get '/games/results', to: 'games#results', as: "results"
  get '/games/suggested', to: 'games#suggested', as: "suggested"

  resources :sessions, only: [:create]
  resources :users, except: [:update, :edit, :delete, :new]

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  get 'register' => 'users#new'
  post 'users' => 'users#create'

  resources :ownerships, only: [:create, :destroy]

  resources :games

  resources :groups, only: [:new, :create, :show]

  resources :memberships, only: [:new, :create, :delete]

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :ownerships
  has_many :owners, through: :ownerships
  has_many :reviews
  has_many :categorizations
  has_many :categories, through: :categorizations

  validates :name, presence: true, uniqueness: true

  def average_rating
    reviews = this.reviews
    reviews.each { |review| review.rating }.reduce(:+) / reviews.length
  end

  def self.search(search_term)
    if search_term
      find(:all, :conditions => ["name LIKE ?", "%#{search}%"])
    else
      Game.all
    end
  end

end

app/controllers/games_controller.rb
require 'open-uri'

class GamesController < ApplicationController
  def new
  end

  def create
  end

  def show
    @comment = Comment.new
    @review = Review.new
    url ="http://www.boardgamegeek.com/xmlapi/boardgame/#{params[:id]}"
    xml_data = open(url)
    read_file = xml_data
    @response_body = Crack::XML.parse(read_file)
    @reviews = Review.where(game_id: params[:id])
    if @response_body["boardgames"]["boardgame"] == nil
      @response_body = nil
      @error = "Sorry, this game does not exist :("
    end
  end

  def index
    if session[:user_id] != nil
      redirect_to user_path id: session[:user_id]
    end
    @user = User.new
    # xml_data = open('http://www.boardgamegeek.com/xmlapi/search?search=Catan')
    # @response_body = Crack::XML.parse(File.read(xml_data))
  end

  def results
    search_q = params[:search]
    xml_data = open("http://www.boardgamegeek.com/xmlapi/search?search=#{search_q.gsub(" ", "%20")}")
    read_file = xml_data
    @response_body = Crack::XML.parse(read_file)
    if @response_body["boardgames"]["boardgame"] == nil
      @response_body = nil
      @error = "Sorry, no results :("
    end
  end

  def suggested
    @suggested_games = {}
    @random_numbers = Array.new(9) {rand(1..10000)}

    @random_numbers.each do |number|
      url ="http://www.boardgamegeek.com/xmlapi/boardgame/#{number}"
      xml_data = open(url)
      read_file = xml_data
      @response_body = Crack::XML.parse(read_file)
      game = @response_body["boardgames"]["boardgame"]
      game["name"].class == Array ? game_name = game["name"][0] : game_name = game["name"]
      @suggested_games[game_name] = [game["thumbnail"], number]
    end

  end

  def destroy
  end

  def update
  end

  def edit
  end
end

app/views/games/index.html.erb
<div class="container">

  <div class="image-container">
    <img class="index-img" src="http://i.imgur.com/H3WDih5.jpg">
    <div class="overlay"><h1>Meet Your Next Game Group</h1></div>
  </div>


  <div class="index-register">
    <h1>Register Today!</h1>
    <%= render partial: "users/form" %>
  </div>
</div>

app/views/games/results.html.erb
<div class="container">

  <% if @response_body != nil %>
    <% @response_body.each do |boardgames| %>
      <% boardgames[1]["boardgame"].each do |game_object| %>
        <div class="game_display">
          <p><a href="/games/<%= game_object["objectid"] %>" ><%=game_object["name"] %></a></p>
          <p><%= game_object["yearpublished"] %></p>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/games/show.html.erb
<div class="container">
  <% game = @response_body["boardgames"]["boardgame"] %>
  <div class="game_header">
    <img src="<%= game['thumbnail'] %>"/>
    <% game["name"].class == Array ? game_name = game["name"][0] : game_name = game["name"] %>
    <h1><%= game_name %></h1><BR>
    Players: <%= game["minplayers"] %> to <%= game["maxplayers"] %> players.<BR>
    Average play time: <%= game["playingtime"] %><BR>
    Year Published: <%= game["yearpublished"] %><BR>
    Average Rating: <%= @reviews.length == 0 ? "This game has not been reviewed yet." : average_rating %><br>
    <%= link_to "Add to your collection", ownerships_path(@ownership, :game_id => game["objectid"]), method: "post" %>
  </div>
   <body>
    <h3>About:</h3>
     <%= game["description"].gsub("<br/>", " ") %>
   </body>

    <%= render "shared/review" %>
  <div class="reviews">
    <% if @reviews %>
      <h2> Reviews </h2>
      <% @reviews.each do |review| %>
        <div class="review-info">
          <h3><%= review.title %></h3>
          <h4><%= User.find(review.reviewer_id).username %></h4>
          <p>Rating: <%= review.rating %>/5</p>
          <%= review.body %>
          <% @review_id = review.id %>
          <% if review.reviewer_id == current_user.id %>
            <%=  button_to "Delete", {controller: 'reviews', action: 'destroy', id: review.id }, method: :delete %>
          <% end %>
        </div>
        <% @comments = review.comments %>
        <% if @comments %>
          <h2> Comments </h2>
            <% @comments.each do |comment| %>
              <p><%= comment.body %></p>
              <%= comment.commenter.username %>
            <% end %>
        <% end %>
        <div class="review-comment-info">
          <%= render "shared/comment" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/games/suggested.html.erb
<div class="container">
  <% @suggested_games.each do |game_name, game_pic_n_number| %>
    <div class="individual-game">
      <div class="game-icon">
        <img src=" <%= game_pic_n_number[0] %> ">
      </div>
      <h4>
        <a href="/games/<%= game_pic_n_number[1] %>"><%= game_name %></a>
      </h4>
    </div>
  <% end %>

</div>